[package]
edition = "2024"
name = "slog"
version = "0.3.0"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.0.0"
glob = "0.3.2"
itertools = "0.14.0"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
